var Config = new Object();

Config.defaultStyle = true;// 是否使用默认主题
Config.titleText = ["", "", ""];//任务名称
Config.contentText = ["", "", ""];//任务说明
Config.rememberText = ["", "", ""]; //记忆阶段顶栏文字
Config.exerciseText = ["", "", ""]; //做题阶段顶栏文字
Config.minLevel = 1; //最低等级数
Config.maxLevel = 5; //最高等级数
Config.startLevel = 1; //起始等级数
Config.questionNumber = 10; //每级题目数
Config.hasRememberView = false; //是否有记忆阶段
Config.hasResultInfo = true; //是否有答题正误提示
Config.hasLevelInfo = true; //是否有级别升降提示
Config.rememberTime = [-1, -1, -1, -1, -1]; //每级的记忆阶段限时（单位：秒，-1为不限时）
Config.exerciseTime = [-1, -1, -1, -1, -1]; //每级的做题阶段限时（单位：秒，-1为不限时）
Config.brainMode = "none";//脑波图显示模式（none无，thinkgear脑电波，hht脑血流）
Config.mustBrain = false;// 是否只有获取到脑血流或脑电数据时才能进行任务
Config.taskTime = 60;//任务时间限制（单位：秒，-1为不限时）
Config.sendRecord = 1;//任务结束时是否回报日志（0不回报，1有数据就回报，2仅在任务到达时间限制后回报）
Config.sendScore = true;//任务结束时是否回报分数